/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./components/Card.vue')['default']
    CardHeader: typeof import('./components/CardHeader.vue')['default']
    Carousel: typeof import('./components/Carousel.vue')['default']
    Container: typeof import('./components/Container.vue')['default']
    DefaultFooter: typeof import('./components/DefaultFooter.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Menu: typeof import('./components/Menu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
